Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/10/2024
Var
nome : caractere
numero_inteiro: inteiro
numero_Quebrado : real
listaDeElementos: vetor de [1..3] de caractere
ligado: logico


Inicio
Escreval("Olá mundo")

escreval(3+3* 8 /2)


Fimalgoritmo